Category.create(name: "SDC3")
Category.create(name: "Light Source")
Category.create(name: "Insaflator")
Category.create(name: "Camera Box")
Category.create(name: "Clarity")
Category.create(name: "Monitor")
